version: '2'
services:
  deuxfabienscarsgo-app:
    image: deuxfabienscarsgo
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://deuxfabienscarsgo-postgresql:5432/DeuxFabiensCarsGo
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  deuxfabienscarsgo-postgresql:
    extends:
      file: postgresql.yml
      service: deuxfabienscarsgo-postgresql
